### ISSUE TITLE
Some formulas do not display properly

### ISSUE THREAD

**Issue by rexislijunyi** [MicrosoftDocs/quantum-docs-pr.zh-CN#1]
I am a Chinese reader,but my Englishis not very well.And this is a professional documen.At first I tried to use Google Translate, but the effect was not good, it translated the superscript and subscript in many formulas. Then I used the official Chinese documentation, but some of the formulas didn't show up and the effect was not good.
Like I said above, my English is not good enough, so I have to use Google Translate, I'm sorry, I hope you can forgive me.
Hope QDK can get better and better.

**Comment by srvbpigh** [comment]
Hello, @rexislijunyi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @rexislijunyi 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?

**Please provide the URL where you found this issue**

Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @rexislijunyi , 

We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 
 
**Please provide the URL where you found this issue**

Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @rexislijunyi 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
