### ISSUE TITLE
Coding Chaos

### ISSUE THREAD

**Issue by gchling** [MicrosoftDocs/quantum-docs-pr.zh-CN#2]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 434e640f-ea90-3c49-9510-1fda8cbee7a1
* Version Independent ID: 9c5af71d-7980-d644-b2bc-9b54bda5e551
* Content: [量程计算中的矢量和矩阵 - Microsoft Quantum](https://docs.microsoft.com/zh-cn/quantum/concepts/vectors-and-matrices)
* Content Source: [articles/concepts/vectors-and-matrices.md](https://github.com/MicrosoftDocs/quantum-docs-pr.zh-CN/blob/live-sxs/articles/concepts/vectors-and-matrices.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by srvbpigh** [comment]
Hello, @gchling
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @gchling, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/quantum-docs-pr/issues/860. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
